create table answer
(
    id          bigint generated by default as identity,
    created_at  timestamp not null,
    updated_at  timestamp,
    contents    clob,
    deleted     boolean   not null,
    question_id bigint,
    writer_id   bigint,
    primary key (id)
);

create table delete_history
(
    id            bigint generated by default as identity,
    content_id    bigint,
    content_type  varchar(255),
    create_date   timestamp,
    deleted_by_id bigint,
    primary key (id)
);

create table question
(
    id        bigint generated by default as identity,
    contents  clob,
    deleted   boolean      not null,
    title     varchar(100) not null,
    writer_id bigint,
    primary key (id)
);

create table station
(
    id         bigint generated by default as identity,
    created_at timestamp   not null,
    updated_at timestamp,
    name       varchar(20) not null,
    primary key (id)
);

create table user
(
    id         bigint generated by default as identity,
    created_at timestamp   not null,
    updated_at timestamp,
    email      varchar(50),
    name       varchar(20) not null,
    password   varchar(20) not null,
    user_id    varchar(20) not null,
    primary key (id)
);

// answer insert
insert
into answer
    (id, created_at, updated_at, contents, deleted, question_id, writer_id)
values (null, ?, ?, ?, ?, ?, ?);

// question insert
insert
into question
    (id, contents, deleted, title, writer_id)
values (null, ?, ?, ?, ?);

// delete_history insert
insert
into
    delete_history
    (id, content_id, content_type, create_date, deleted_by_id)
values
    (null, ?, ?, ?, ?);

// answer 업데이트
update
    answer
set updated_at=?,
    contents=?,
    deleted=?,
    question_id=?,
    writer_id=?
where id = ?;
