package homework.domain.entity;

import homework.domain.entity.common.TraceDate;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;

/**
 * create table question
 * (
 *     id         bigint generated by default as identity,
 *     contents   clob,
 *     created_at timestamp    not null,
 *     deleted    boolean      not null,
 *     title      varchar(100) not null,
 *     updated_at timestamp,
 *     writer_id  bigint,
 *     primary key (id)
 * )
 */
@Getter
@NoArgsConstructor
@Entity
public class Question extends TraceDate {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Lob
    private String contents;

    @Column(length = 100, nullable = false)
    private String title;

    @Column(nullable = false)
    private boolean deleted;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "writer_id")
    private User user;

    @OneToMany(mappedBy = "question")
    List<Answer> answers = new ArrayList<>();

    @Builder
    private Question(String contents, String title, User user) {
        this.contents = contents;
        this.title = title;
        this.user = user;
        this.deleted = false;
    }
}
