package homework.domain.entity;

import homework.domain.entity.common.TraceDate;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;

/**
 * create table user
 * (
 *     id         bigint generated by default as identity,
 *     created_at timestamp   not null,
 *     email      varchar(50),
 *     name       varchar(20) not null,
 *     password   varchar(20) not null,
 *     updated_at timestamp,
 *     user_id    varchar(20) not null,
 *     primary key (id)
 * )
 *
 * alter table user
 *     add constraint UK_a3imlf41l37utmxiquukk8ajc unique (user_id)
 */

@Getter
@NoArgsConstructor
@Entity
@Table(uniqueConstraints = @UniqueConstraint(name = "unique_user_id", columnNames={"userId"}))
public class User extends TraceDate {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(length = 50)
    private String email;

    @Column(length = 20, nullable = false)
    private String name;

    @Column(length = 20, nullable = false)
    private String password;

    @Column(length = 20, nullable = false)
    private String userId;

    @OneToMany(mappedBy = "user")
    private List<Question> questions = new ArrayList<>();

    @Builder
    private User(String email, String name, String password, String userId) {
        this.email = email;
        this.name = name;
        this.password = password;
        this.userId = userId;
    }
}
