package subway.domain;

import javax.persistence.*;

/**
 * create table station (
 *      id bigint generated by default as identity,
 *      name varchar(255) not null,
 *      primary key (id)
 * )
 */
@Entity
@Table(name = "station")
public class Station {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false)
    private String name;

    @ManyToOne
    @JoinColumn(name = "line_id")
    private Line line;

//    @OneToOne
//    @JoinColumn(name = "line_station_id")
//    private LineStation lineStation;

    @OneToOne(mappedBy = "station")
    private LineStation lineStation;

    /**
     * protected인 이유
     *  - JSP가 권장
     *  - Lazy Loading과 연관 되어 있음
     */
    protected Station() {}

    public Station(final String name) {
        this.name = name;
    }

    public Station(final String name, final LineStation lineStation) {
        this.name = name;
        this.lineStation = lineStation;
    }

    public Long getId() {
        return this.id;
    }

    public String getName() {
        return this.name;
    }

    public void changeName(final String name) {
        this.name = name;
    }

    public void setLine(final Line line) {
        this.line = line;
        line.getStations().add(this);
    }

    public Line getLine() {
        return this.line;
    }
}
