package qna.subway;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * create table line (
 * id bigint generated by default as identity,
 * name varchar(255) not null,
 * primary key (id)
 * )
 * <p>
 * create table station (
 * id bigint generated by default as identity,
 * name varchar(255) not null,
 * line_id bigint,
 * primary key (id)
 * )
 * <p>
 * alter table station
 * add constraint FKklalypfiiahjy57wtapf4w92
 * foreign key (line_id)
 * references line
 */
@Entity
@Table(name = "station")
public class Station {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false)
    private String name;

    @ManyToOne
    private Line line;

    protected Station() {

    }
}
